stages:         
# Set up two testing paths
  - test
  - deploy
  - release

# Published matlab-batch image, link provided by Jos M.   
# MATLAB_BATCH_TOKEN is established as a GitLab CI/CD variable
.matlab_batch_defaults:
  image: 
    name: 677276097160.dkr.ecr.us-east-1.amazonaws.com/external-git/matlab-gitrunner-image:R2024b-latest
    entrypoint: [""]

smoke-test:
# Smoke tests should run all the time
    extends: .matlab_batch_defaults
    tags:
    # Add additional tags like (e.g. - arduino) as required
    # Make sure that the runner you plan to use matches the tags
      - mathworks.matlab.cloud-linux-kubernetes
    stage: test
    script: 
      - export MLM_LICENSE_TOKEN="$LICENSEOWNER|$LICENSELABEL|$LICENSETOKEN" # Set the batch token license
      - xvfb-run matlab-batch "openProject(pwd);RunAllTests"
    when: always
    allow_failure: true
    artifacts:
      name: "$VERSION"
      paths:
        - public/*
      when:  always


pages:
    extends: .matlab_batch_defaults
    tags:
      - mathworks.matlab.cloud-linux-kubernetes
    stage: deploy
    script:
      - export MLM_LICENSE_TOKEN="$LICENSEOWNER|$LICENSELABEL|$LICENSETOKEN" # Set the batch token license
      - xvfb-run matlab-batch "openProject(pwd);PostSmokeTest;"
    artifacts:
        paths:
            - public
        
file-test:   
    extends: .matlab_batch_defaults
    tags:
      - mathworks.matlab.cloud-linux-kubernetes
    stage: release
    script: 
      - export MLM_LICENSE_TOKEN="$LICENSEOWNER|$LICENSELABEL|$LICENSETOKEN" # Set the batch token license
      - xvfb-run matlab-batch "proj = openProject(pwd); 
        addpath(proj.RootFolder+'/InternalFiles/Tests/CI');
        results = runtests('OpenCloseFileTest.m');
        disp(table(results)); assertSuccess(results);"
    rules:
# This test should always run when merging to main
# And be available for manual running on any push
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
        when: always
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
        when: manual
    allow_failure: true

# release-testing:
#     tags:
#      - matlab
#    stage: release
#    script: 
#      - matlab -batch "proj = openProject(pwd); 
#        cd ..;
#        addpath(genpath(fullfile('utilities','TestingResources')));
#        addpath(genpath(fullfile('utilities','Tools')));
#        runCMTests"
#    rules:
## This test should always run when merging to main
## And be available for manual running on any push
#      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
#        when: always
#      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
#        when: manual
#    allow_failure: true
